package com.kibot.core

data class LeaseProtocolConfig(
    val heartbeatIntervalSeconds: Int = 10,
    val leaseTtlSeconds: Int = 30,
)

data class PairSelectionPolicy(
    val minDailyQuoteVolumeIdr: Double = 10_000_000.0,
    val smallCapitalMinDailyQuoteVolumeIdr: Double = 280_000.0,
    val smallCapitalMinTop5DepthIdr: Double = 10_000.0,
    val smallCapitalMinTradeCount24h: Int = 14,
    val smallCapitalMaxSpreadPct: Double = 1.25,
    val smallCapitalMaxSlippagePct: Double = 1.20,
    val maxSpreadPct: Double = 0.88,
    val maxEstimatedSlippagePct: Double = 0.92,
    val minOrderBookStabilityScore: Double = 0.34,
    val minRecentTradeActivityScore: Double = 0.24,
    val minFillQualityScore: Double = 0.28,
    val minHistoricalExpectancyScore: Double = 0.32,
    val minTierAScore: Double = 0.72,
    val minTierBScore: Double = 0.52,
    val minHoldabilityForSwing: Double = 0.62,
    val minTrendScoreForSwing: Double = 0.60,
    val idealVolatilityPct: Double = 2.25,
    val maxAcceptedVolatilityPct: Double = 8.0,
    val minFeeAdjustedEdgeScore: Double = 0.24,
    val estimatedMakerRoundTripCostPct: Double = 0.52,
    val estimatedTakerRoundTripCostPct: Double = 0.78,
    val feeSafetyBufferPct: Double = 0.10,
    val strongNetEdgePct: Double = 1.60,
    val shortlistSize: Int = 128,
    val prefilterCandidatePoolSize: Int = 420,
    val blockedBaseAssets: Set<String> = setOf("usdt", "usdc", "indr"),
    val stagnantShortTermReturnPctMax: Double = 0.60,
    val stagnantMediumTermReturnPctMax: Double = 1.20,
    val speculativeMinShortTermReturnPct: Double = 3.4,
    val speculativeMaxShortTermReturnPct: Double = 220.0,
    val speculativeMinMediumTermReturnPct: Double = 0.8,
    val speculativeMinTradeActivityScore: Double = 0.42,
    val speculativeMinDepthScore: Double = 0.18,
    val speculativeMinHistoricalExpectancyScore: Double = 0.10,
)

data class RiskConfig(
    val hardDailyLossLimitPct: Double = 0.25,
    val warningDrawdownPct: Double = 0.05,
    val reduceSizeDrawdownPct: Double = 0.08,
    val defensiveDrawdownPct: Double = 0.12,
    val restrictedEntriesDrawdownPct: Double = 0.15,
    val stopNewEntriesDrawdownPct: Double = 0.18,
    val maxConcurrentPositions: Int = 6,
    val minimumCashReservePct: Double = 0.01,
    val defensiveCashReservePct: Double = 0.40,
    val attackCashReservePct: Double = 0.01,
    val maxPerPositionBudgetPct: Double = 0.98,
    val targetMinPositionBudgetIdr: Double = 28_000.0,
    val minSecondSlotRankingScore: Double = 0.66,
    val minSecondSlotOpportunityScore: Double = 0.56,
    val singlePositionBudgetBoostMultiplier: Double = 1.55,
    val multiPositionBudgetSplitMultiplier: Double = 1.08,
    val reducedSizeMultiplier: Double = 0.75,
    val defensiveSizeMultiplier: Double = 0.50,
    val attackSizeMultiplier: Double = 1.25,
    val dominantTierAReserveReliefPct: Double = 0.04,
    val dominantTierAMinCashReservePct: Double = 0.06,
    val speculativePocketMaxEquityPct: Double = 0.35,
    val loserHeatCautionPct: Double = 0.010,
    val loserHeatHardBrakePct: Double = 0.018,
    val top1DeployableConcentrationMaxPct: Double = 0.45,
    val top2DeployableConcentrationMaxPct: Double = 0.70,
    val dominantAllInRankingScoreMin: Double = 0.84,
    val dominantAllInOpportunityScoreMin: Double = 0.74,
    val dominantAllInGapMin: Double = 0.09,
    val dominantAllInMaxAllocationPct: Double = 0.995,
    val rotationRankingGapMin: Double = 0.05,
    val rotationMinNetUpgradePct: Double = 1.20,
    val rotationMinClearProfitPct: Double = 0.60,
    val rotationMinClearProfitIdr: Double = 80.0,
    val blockEntriesBelowBatteryPct: Int = 18,
    val suggestTakeoverBelowBatteryPct: Int = 30,
)

data class MarketRegimePolicy(
    val healthyUptrendTrendScoreMin: Double = 0.58,
    val healthyUptrendOpportunityMin: Double = 0.62,
    val panicTrendScoreMax: Double = 0.24,
    val panicMicrostructureMax: Double = 0.40,
    val unclearMicrostructureMax: Double = 0.48,
)

data class BotModePolicy(
    val attackOpportunityScoreMin: Double = 0.78,
    val attackBotHealthScoreMin: Double = 0.82,
    val attackPerformanceScoreMin: Double = 0.65,
    val growthOpportunityScoreMin: Double = 0.55,
    val growthBotHealthScoreMin: Double = 0.62,
)

data class ProfitProtectionConfig(
    val weeklyProfitGuardPct: Double = 0.06,
    val givebackWarningPct: Double = 0.18,
    val coolingGivebackPct: Double = 0.30,
    val trailingGuardMultiplier: Double = 0.90,
    val coolingAggressionMultiplier: Double = 0.65,
)

data class WeeklyLearningConfig(
    val minimumTradeSamples: Int = 10,
    val minimumPairSamples: Int = 3,
    val maximumWhitelistPairs: Int = 4,
    val maximumBlacklistPairs: Int = 5,
    val maxAggressionDeltaPerReview: Double = 0.05,
    val maxSizeDeltaPerReview: Double = 0.05,
    val maxBiasDeltaPerReview: Double = 0.10,
)

data class StrategyExecutionConfig(
    val minOrderNotionalIdr: Double = 15_000.0,
    val entrySpendBufferPct: Double = 0.002,
    val growthMinRankingScore: Double = 0.63,
    val defensiveMinRankingScore: Double = 0.82,
    val attackMinRankingScore: Double = 0.52,
    val minExpectedOpportunityScore: Double = 0.42,
    val candidateCount: Int = 160,
    val maxExecutableEntriesPerCycle: Int = 4,
    val productiveIdleRankingDelta: Double = 0.09,
    val productiveIdleOpportunityDelta: Double = 0.08,
    val minExpectedNetProfitIdr: Double = 200.0,
    val minExpectedNetProfitIdrSpeculative: Double = 220.0,
    val minProfitToCostMultiplier: Double = 1.10,
    val minProfitAfterFeesBufferIdr: Double = 55.0,
    val minNetEdgeAfterCostsBufferPct: Double = 0.0,
    val marketEntryEnabled: Boolean = true,
    val marketEntryMinRankingScore: Double = 0.46,
    val marketEntryMinExpectedNetProfitPct: Double = 0.30,
    val marketEntryMaxSpreadPct: Double = 0.90,
    val marketEntryMaxSlippagePct: Double = 0.82,
    val marketEntryTightSpreadPct: Double = 0.68,
    val marketEntryTightSlippagePct: Double = 0.60,
    val marketEntryMinTradeActivityScore: Double = 0.42,
    val marketEntryMinTrendScore: Double = 0.48,
    val pairReentryCooldownSeconds: Int = 12,
    val breakoutAggressiveEntryMinRankingScore: Double = 0.40,
    val breakoutAggressiveEntryMinExpectedNetProfitPct: Double = 0.22,
    val breakoutAggressiveEntryMinShortTermReturnPct: Double = 1.5,
    val breakoutAggressiveEntryMinMediumTermReturnPct: Double = 0.35,
    val executionAllowedQuoteAssets: Set<String> = setOf("idr"),
)
