create table if not exists public.profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    email text,
    display_name text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.bots (
    bot_id text primary key,
    user_id uuid not null references public.profiles(user_id) on delete cascade,
    display_name text not null,
    timezone text not null default 'Asia/Jakarta',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (user_id, display_name)
);

create table if not exists public.devices (
    device_id text primary key,
    user_id uuid not null references public.profiles(user_id) on delete cascade,
    display_name text not null,
    platform public.device_platform not null,
    role public.device_role not null,
    is_revoked boolean not null default false,
    last_seen_at timestamptz,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.bot_state (
    bot_id text primary key references public.bots(bot_id) on delete cascade,
    desired_state public.bot_desired_state not null default 'OFF',
    effective_state public.bot_effective_state not null default 'STOPPED',
    active_device_id text references public.devices(device_id),
    standby_device_id text references public.devices(device_id),
    current_term bigint not null default 0,
    sync_health public.sync_health not null default 'DEGRADED',
    strategy_mode text not null default 'AUTO_CONSERVATIVE',
    safe_mode_reason text,
    current_pair text,
    last_heartbeat_at timestamptz,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.engine_leases (
    bot_id text primary key references public.bots(bot_id) on delete cascade,
    holder_device_id text references public.devices(device_id),
    current_term bigint not null default 0,
    state public.lease_state not null default 'RELEASED',
    expires_at timestamptz,
    last_heartbeat_at timestamptz,
    conflict_detected boolean not null default false,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.engine_heartbeats (
    heartbeat_id bigint generated by default as identity primary key,
    bot_id text not null references public.bots(bot_id) on delete cascade,
    device_id text not null references public.devices(device_id) on delete cascade,
    observed_at timestamptz not null default timezone('utc', now()),
    term bigint,
    is_master boolean not null default false,
    desired_state public.bot_desired_state not null,
    effective_state public.bot_effective_state not null,
    sync_health public.sync_health not null,
    health_status public.health_status not null,
    websocket_healthy boolean not null default false,
    exchange_reachable boolean not null default false,
    supabase_reachable boolean not null default false,
    battery_percent integer,
    charging boolean,
    network_metered boolean,
    heartbeat_lag_ms bigint,
    last_error text,
    warnings jsonb not null default '[]'::jsonb
);

create table if not exists public.command_queue (
    command_id uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    created_by_device_id text not null references public.devices(device_id),
    target_device_id text references public.devices(device_id),
    command_type public.command_type not null,
    status public.command_status not null default 'QUEUED',
    payload jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    expires_at timestamptz,
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.api_credentials_encrypted (
    credential_id uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    user_id uuid not null references public.profiles(user_id) on delete cascade,
    cipher_version text not null,
    kdf_algorithm text not null default 'argon2id',
    kdf_params jsonb not null,
    secret_bundle_ciphertext text not null,
    secret_bundle_nonce text not null,
    secret_bundle_salt text not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (bot_id, user_id)
);

create table if not exists public.execution_actions (
    action_id uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    device_id text not null references public.devices(device_id) on delete cascade,
    term bigint not null,
    order_intent_id text not null,
    action_type text not null check (action_type in ('submit_order', 'cancel_order')),
    status text not null check (status in ('RESERVED', 'SUBMITTED', 'RECONCILED', 'EXPIRED', 'FAILED')) default 'RESERVED',
    metadata jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    expires_at timestamptz not null,
    completed_at timestamptz
);

create table if not exists public.orders (
    order_pk uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    term bigint not null,
    device_id text not null references public.devices(device_id),
    pair_id text not null,
    exchange_order_id text,
    client_order_id text not null,
    side public.order_side not null,
    order_type public.order_type not null,
    status public.order_status not null default 'CREATED',
    price numeric(38, 18),
    quantity numeric(38, 18) not null,
    executed_quantity numeric(38, 18) not null default 0,
    remaining_quantity numeric(38, 18) not null default 0,
    fee_paid numeric(38, 18) not null default 0,
    opened_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    unique (bot_id, client_order_id)
);

create table if not exists public.fills (
    fill_pk uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    order_pk uuid references public.orders(order_pk) on delete set null,
    exchange_fill_id text,
    exchange_order_id text,
    pair_id text not null,
    side public.order_side not null,
    quantity numeric(38, 18) not null,
    price numeric(38, 18) not null,
    fee numeric(38, 18) not null default 0,
    fee_asset text not null,
    executed_at timestamptz not null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.positions (
    position_id uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    pair_id text not null,
    base_asset text not null,
    quote_asset text not null,
    state public.position_state not null default 'OPENING',
    quantity numeric(38, 18) not null,
    average_entry_price numeric(38, 18) not null,
    realized_pnl_idr numeric(38, 18) not null default 0,
    unrealized_pnl_idr numeric(38, 18) not null default 0,
    opened_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.daily_equity (
    bot_id text not null references public.bots(bot_id) on delete cascade,
    equity_date date not null,
    opening_equity_idr numeric(38, 18) not null,
    current_equity_idr numeric(38, 18) not null,
    realized_pnl_idr numeric(38, 18) not null default 0,
    unrealized_pnl_idr numeric(38, 18) not null default 0,
    drawdown_pct numeric(12, 6) not null default 0,
    hard_daily_loss_limit_pct numeric(12, 6) not null default 0.25,
    hard_stop_triggered boolean not null default false,
    rebase_pending boolean not null default false,
    updated_at timestamptz not null default timezone('utc', now()),
    primary key (bot_id, equity_date)
);

create table if not exists public.risk_events (
    risk_event_id uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    device_id text references public.devices(device_id),
    event_type public.risk_event_type not null,
    severity public.log_level not null,
    details jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.logs (
    log_id bigint generated by default as identity primary key,
    bot_id text not null references public.bots(bot_id) on delete cascade,
    device_id text references public.devices(device_id),
    term bigint,
    level public.log_level not null,
    category text not null,
    message text not null,
    metadata jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.strategy_metrics (
    metric_id bigint generated by default as identity primary key,
    bot_id text not null references public.bots(bot_id) on delete cascade,
    pair_id text not null,
    liquidity_score numeric(12, 6) not null,
    spread_score numeric(12, 6) not null,
    slippage_score numeric(12, 6) not null,
    stability_score numeric(12, 6) not null,
    fee_adjusted_edge_score numeric(12, 6) not null,
    rejection_reasons jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.market_snapshots (
    snapshot_id bigint generated by default as identity primary key,
    bot_id text not null references public.bots(bot_id) on delete cascade,
    pair_id text not null,
    best_bid numeric(38, 18) not null,
    best_ask numeric(38, 18) not null,
    mid_price numeric(38, 18) not null,
    spread_pct numeric(12, 6) not null,
    quote_volume_24h numeric(38, 18) not null,
    base_volume_24h numeric(38, 18) not null,
    estimated_slippage_pct numeric(12, 6) not null,
    order_book_stability_score numeric(12, 6) not null,
    captured_at timestamptz not null
);

create table if not exists public.cleanup_runs (
    cleanup_run_id uuid primary key default gen_random_uuid(),
    bot_id text not null references public.bots(bot_id) on delete cascade,
    started_at timestamptz not null default timezone('utc', now()),
    finished_at timestamptz,
    status text not null check (status in ('RUNNING', 'SUCCEEDED', 'FAILED')),
    retention_days integer not null default 90,
    deleted_rows jsonb not null default '{}'::jsonb,
    error_message text
);

create table if not exists public.daily_trade_summary (
    bot_id text not null references public.bots(bot_id) on delete cascade,
    summary_date date not null,
    trade_count integer not null default 0,
    win_count integer not null default 0,
    loss_count integer not null default 0,
    gross_volume_idr numeric(38, 18) not null default 0,
    realized_pnl_idr numeric(38, 18) not null default 0,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    primary key (bot_id, summary_date)
);

create index if not exists idx_devices_user on public.devices(user_id);
create index if not exists idx_heartbeats_bot_observed on public.engine_heartbeats(bot_id, observed_at desc);
create index if not exists idx_commands_bot_created on public.command_queue(bot_id, created_at desc);
create index if not exists idx_execution_actions_bot_expires on public.execution_actions(bot_id, expires_at);
create index if not exists idx_orders_bot_updated on public.orders(bot_id, updated_at desc);
create index if not exists idx_orders_bot_status on public.orders(bot_id, status);
create index if not exists idx_fills_bot_executed on public.fills(bot_id, executed_at desc);
create index if not exists idx_positions_bot_state on public.positions(bot_id, state);
create index if not exists idx_logs_bot_created on public.logs(bot_id, created_at desc);
create index if not exists idx_market_snapshots_bot_pair_captured on public.market_snapshots(bot_id, pair_id, captured_at desc);
create index if not exists idx_strategy_metrics_bot_pair_created on public.strategy_metrics(bot_id, pair_id, created_at desc);

